name: Olyvoo Auto Deploy

on:
  push:
    branches:
      - main # main branch'e her push yaptığında çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3

      - name: Node.js Kur
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Al
        run: |
          npm install
          npm run build

      - name: AWS Kimlik Tanımla
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 # Bucket'ın hangi bölgedeyse (örn: us-east-1)

      - name: S3'e Gönder
        run: |
          aws s3 sync out/ s3://olyvoo-landing --delete

      - name: CloudFront Önbelleğini Temizle
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"